CREATE TABLE TA_ACHIEVEMENT_CATEGORY (
		CATEGORY_ID CHAR(2) NOT NULL,
		DESCRIPTION VARCHAR(40),
        PRIMARY KEY (CATEGORY_ID)
	);

CREATE TABLE TA_USERS (
		EMAIL_ADDRESS VARCHAR(80) NOT NULL,
		PASSWORD CHAR(32) NOT NULL,
		ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL,
		USER_ROLE VARCHAR(8) NOT NULL,
        PRIMARY KEY (EMAIL_ADDRESS)
	);

CREATE TABLE TA_EMPLOYEE_DETAIL (
		EMPLOYEE_ID CHAR(6) NOT NULL,
		EMAIL_ADDRESS VARCHAR(80) NOT NULL,
		FIRST_NAME VARCHAR(30) NOT NULL,
		LAST_NAME VARCHAR(30) NOT NULL,
		MANAGER_ID CHAR(6) NOT NULL,
		MANAGER_FLAG CHAR(1) DEFAULT 'N' NOT NULL,
        PRIMARY KEY (EMPLOYEE_ID)
	);

CREATE TABLE TA_ACHIEVEMENT_DOCUMENTS (
		DOCUMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
		ACHIEVEMENT_ID BIGINT NOT NULL,
		DOCUMENT_CONTENT BLOB(102400) NOT NULL,
        PRIMARY KEY (DOCUMENT_ID)
	);

CREATE TABLE TA_EMPLOYEE_PROJECT (
		PROJECT_ID CHAR(11) NOT NULL,
		EMPLOYEE_ID CHAR(6) NOT NULL,
		START_DATE DATE NOT NULL,
		END_DATE DATE,
        PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID)
	);

CREATE TABLE TA_ACHIEVEMENT_TYPE (
		TYPE_ID CHAR(2) NOT NULL,
		DESCRIPTION VARCHAR(40) NOT NULL,
        PRIMARY KEY (TYPE_ID)
	);

CREATE TABLE TA_ACHIEVEMENT (
		ACHIEVEMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
		EMPLOYEE_ID CHAR(6) NOT NULL,
		TYPE_ID CHAR(2) NOT NULL,
		PROJECT_ID CHAR(11),
		ACHIEVEMENT_TEXT VARCHAR(5000) NOT NULL,
		START_DATE DATE NOT NULL,
		END_DATE DATE,
		STATUS_CODE CHAR(1) DEFAULT 'N' NOT NULL,
		APPROVER_ID CHAR(6) NOT NULL,
		APPROVER_COMMENT_TEXT VARCHAR(5000),
		CATEGORY_ID CHAR(2),
		APPROVER_POINT_VAL INT DEFAULT 0,
        PRIMARY KEY (ACHIEVEMENT_ID)
	);

CREATE TABLE TA_PROJECTS (
		PROJECT_ID CHAR(11) NOT NULL,
		PROJECT_NAME VARCHAR(80) NOT NULL,
		MANAGER_ID CHAR(6) NOT NULL,
        PRIMARY KEY (PROJECT_ID)
	);

ALTER TABLE TA_ACHIEVEMENT ADD CONSTRAINT TA_AC_TA_APPVR_FK FOREIGN KEY (APPROVER_ID)
	REFERENCES TA_EMPLOYEE_DETAIL (EMPLOYEE_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_EMPLOYEE_PROJECT ADD CONSTRAINT TA_EMPL_TA_EMP_FK FOREIGN KEY (EMPLOYEE_ID)
	REFERENCES TA_EMPLOYEE_DETAIL (EMPLOYEE_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_ACHIEVEMENT_DOCUMENTS ADD CONSTRAINT ACHIEVEMEN_TA_A_FK FOREIGN KEY (ACHIEVEMENT_ID)
	REFERENCES TA_ACHIEVEMENT (ACHIEVEMENT_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_ACHIEVEMENT ADD CONSTRAINT TA_A_ACHIEVEMEN_FK FOREIGN KEY (CATEGORY_ID)
	REFERENCES TA_ACHIEVEMENT_CATEGORY (CATEGORY_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_EMPLOYEE_DETAIL ADD CONSTRAINT TA_EMPLOYE_TA_U_FK FOREIGN KEY (EMAIL_ADDRESS)
	REFERENCES TA_USERS (EMAIL_ADDRESS)
	ON DELETE CASCADE;

ALTER TABLE TA_ACHIEVEMENT ADD CONSTRAINT TA_ACH_ACHIEVEM_FK FOREIGN KEY (TYPE_ID)
	REFERENCES TA_ACHIEVEMENT_TYPE (TYPE_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_EMPLOYEE_DETAIL ADD CONSTRAINT TA_EMPL_TA_EMPL_FK FOREIGN KEY (MANAGER_ID)
	REFERENCES TA_EMPLOYEE_DETAIL (EMPLOYEE_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_PROJECTS ADD CONSTRAINT TA_P_TA_EMPLOYE_FK FOREIGN KEY (MANAGER_ID)
	REFERENCES TA_EMPLOYEE_DETAIL (EMPLOYEE_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_ACHIEVEMENT ADD CONSTRAINT TA_AC_TA_EMPLOY_FK FOREIGN KEY (EMPLOYEE_ID)
	REFERENCES TA_EMPLOYEE_DETAIL (EMPLOYEE_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_ACHIEVEMENT ADD CONSTRAINT TA_ACHIE_TA_PR_FK FOREIGN KEY (PROJECT_ID)
	REFERENCES TA_PROJECTS (PROJECT_ID)
	ON DELETE CASCADE;

ALTER TABLE TA_EMPLOYEE_PROJECT ADD CONSTRAINT TA_EMPLOYE_TA_P_FK FOREIGN KEY (PROJECT_ID)
	REFERENCES TA_PROJECTS (PROJECT_ID)
	ON DELETE CASCADE;

